name: letzrentnew
description: A new Flutter project.

version: 6.0.34+176

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_messaging: ^15.0.0
  firebase_crashlytics: ^4.0.0
  firebase_dynamic_links: ^6.0.0

  provider: ^6.1.1
  intl: ^0.19.0
  razorpay_flutter: ^1.3.6
  image_picker: ^1.0.4
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.2.6
  carousel_slider_plus: ^6.0.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  http: ^1.2.1
  shared_preferences: ^2.0.13
  confetti: ^0.7.0
  mixpanel_flutter: ^2.0.0
  flutter_spinkit: ^5.1.0
  tap_debouncer: ^2.0.0
  in_app_review: ^2.0.4
  # place_picker: ^0.10.0
  flutter_screenutil: ^5.5.2
  geolocator: ^12.0.0
# package_info_plus: ^8.0.0
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^6.1.0
  google_fonts: ^6.2.1
  # connectivity_plus: ^6.0.3
  appsflyer_sdk: ^6.13.0+1
  firebase_analytics: ^11.0.0
  fluttertoast: ^8.2.5
  google_maps_flutter: ^2.5.0
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo/zymo_logo/zymo_logo.jpg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_logo/zymo_logo/zymo_logo.jpg"
  adaptive_icon_padding: true

flutter_native_splash:
  color: "#000000"
  image: assets/app_logo/zymo_logo/zymo_logo.jpg
  branding: assets/app_logo/zymo_logo/zymo_logo.jpg
  color_dark: "#000000"
  image_dark: assets/app_logo/zymo_logo/zymo_logo.jpg
  branding_dark: assets/app_logo/zymo_logo/zymo_logo.jpg
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/HomeIcons/
    - assets/images/Tips&Tricks/
    - assets/images/ZymoBenefits/
    - assets/images/brands/
    - assets/images/topCars/
    - assets/images/NewCars/
    - dev_assets/
    - assets/app_logo/zymo_logo/

  fonts:
    - family: Garamond
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf
          style: italic
