// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkfsTD8o5HaNXSDl7j6Sog_2o8kHXII8s',
    appId: '1:912635063803:android:84249ef7b9b62398e22f5e',
    messagingSenderId: '912635063803',
    projectId: 'letzrent-5f5a3',
    databaseURL: 'https://letzrent-5f5a3.firebaseio.com',
    storageBucket: 'letzrent-5f5a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNzmwm88w-YSP90VwMmS4Zd3JxpYziklQ',
    appId: '1:912635063803:ios:35b82cdd7490dfe8e22f5e',
    messagingSenderId: '912635063803',
    projectId: 'letzrent-5f5a3',
    databaseURL: 'https://letzrent-5f5a3.firebaseio.com',
    storageBucket: 'letzrent-5f5a3.appspot.com',
    androidClientId: '912635063803-3cv4gofb9ihh1rro4s629smejh1kjsqp.apps.googleusercontent.com',
    iosClientId: '912635063803-p64v02b37fj0gn73jmo6gfbokrmj5p6l.apps.googleusercontent.com',
    iosBundleId: 'com.letzrent.letzrent',
  );
}
